// Generated by Haxe 3.4.0
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
public class BingoAdventure : global::HaxeModuleRules {
	
	public BingoAdventure(global::UnrealBuildTool.TargetInfo target) : base(target) {
		this.PublicDependencyModuleNames.Add(((string) ("GameMenuBuilder") ));
		global::haxe.root.Helpers.addRange_String(this.PrivateDependencyModuleNames, new global::haxe.root.Array<object>(new object[]{"Slate", "SlateCore"}));
	}
	
	
	public override object getConfig() {
		return base.getConfig();
	}
	
	
}


